<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Accessor\Data.Accessor.csproj" />
    <ProjectReference Include="..\Data.Database\Data.Database.csproj" />
    <ProjectReference Include="..\Logic.Shared\Logic.Shared.csproj" />
    <ProjectReference Include="..\Shared.Models\Shared.Models.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

</Project>
